CREATE DATABASE IF NOT EXISTS ${MYSQL_DATA}; 
CREATE USER IF NOT EXISTS '${MYSQL_ADMIN}'@'%' IDENTIFIED by '${MYSQL_PASS}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATA}.* TO '${MYSQL_ADMIN}'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED by '${MYSQL_ROOT_PASS}';
FLUSH PRIVILEGES;
