version: '3'

services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_DATA: ${MYSQL_DATA}
        MYSQL_ADMIN: ${MYSQL_ADMIN}
        MYSQL_PASS: ${MYSQL_PASS}
        MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    restart: unless-stopped
    networks:
      - inception
    env_file: .env
    build:
      context: ./requirements/wordpress
      args:
        MYSQL_DATA: ${MYSQL_DATA}
        MYSQL_ADMIN: ${MYSQL_ADMIN}
        MYSQL_PASS: ${MYSQL_PASS}
        MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  
networks:
  inception:

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/malbrand/data
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/malbrand/data
      o: bind

