version: '3.1'

services:
  mariadb:
    container_name: mariadb
    build: /docker/mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - /home/malbrand/data
    environement:
      - MYSQL_ROOT_PASSWORD${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD${MYSQL_PASSWORD}
      - MYSQL_DATABASE${MYSQL_DATABASE}
    networks:
      - inception
