version: "3"

services:

####                NGINX                ####    
   wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    env_file: .env
    
networks:
  inception:
