version: '3'
services:
   nginx:
      container_name: nginx
      build: ./requirements/nginx
      image: nginx
      env_file: .env
      ports:
        - 443:443
      networks:
        - inception
      restart: always
      depends_on:
        - wordpress

   mariadb:
      container_name: mariadb
      build: ./requirements/mariadb
      image: mariadb
      env_file: .env
      ports:
        - "3306:3306"
      networks:
        - inception
          # volumes:
          #- db_data:/var/lib/mysql
      restart: always

   wordpress:
      container_name: wordpress
      build: ./requirements/wordpress
      image: wordpress
      env_file: .env
      networks:
        - inception
      restart: always
      depends_on:
        - mariadb
networks:
  inception:

    #volumes:

    #db_data:
    #driver: local
    #driver_opts:
    # type: none
    # device: /home/malbrand/data/mariadb
    # o: bind

