version: '3'

services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_DATA: ${MYSQL_DATA}
        MYSQL_ADMIN: ${MYSQL_ADMIN}
        MYSQL_PASS: ${MYSQL_PASS}
        MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASS}
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"

  
networks:
  inception:

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/malbrand/data/
      o: bind

